
package br.com.idtrust.icarta.ws.v200;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EmailRastreadoIntegracao", targetNamespace = "http://webservice.icarta.pro/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EmailRastreadoIntegracao {


    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.idtrust.icarta.ws.v200.GetPericiaResponse
     */
    @WebMethod(action = "http://webservice.icarta.pro/getPericia")
    @WebResult(name = "getPericiaResponse", targetNamespace = "http://webservice.icarta.pro/", partName = "parameters")
    public GetPericiaResponse getPericia(
        @WebParam(name = "getPericia", targetNamespace = "http://webservice.icarta.pro/", partName = "parameters")
        GetPericia parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns br.com.idtrust.icarta.ws.v200.SendEmailResponse
     */
    @WebMethod(action = "http://webservice.icarta.pro/sendEmail")
    @WebResult(name = "sendEmailResponse", targetNamespace = "http://webservice.icarta.pro/", partName = "parameters")
    public SendEmailResponse sendEmail(
        @WebParam(name = "sendEmail", targetNamespace = "http://webservice.icarta.pro/", partName = "parameters")
        SendEmail parameters);

}
